apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    component: mongo
spec:
  type: NodePort
  selector:
    component: mongo
  ports:
  - name: db
    port: 27017
    protocol: TCP
